### ISSUE TITLE
error when reproducing the geolift example in the documentation

### ISSUE THREAD

**Issue by xinliy123** [pymc-labs/CausalPy#246] opened 2023-09-21 08:03 UTC
I encountered an error when reproducing the geolift example, I got the error:

---------------------------------------------------------------------------
---------------------------------------------------------------------------
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[2], line 22
     13 result = cp.pymc_experiments.RegressionDiscontinuity(
     14     df,
     15     formula="all ~ 1 + age + treated",
   (...)
     18     treatment_threshold=21,
     19     )
     21 # Visualize outputs
---> 22 fig, ax = result.plot();
     24 # Get a results summary
     25 result.summary()

File ~/anaconda3/lib/python3.9/site-packages/causalpy/pymc_experiments.py:914, in RegressionDiscontinuity.plot(self)
    912 fig, ax = plt.subplots()
    913 # Plot raw data
--> 914 sns.scatterplot(
    915     self.data,
    916     x=self.running_variable_name,
    917     y=self.outcome_variable_name,
    918     c="k",  # hue="treated",
    919     ax=ax,
    920 )
    922 # Plot model fit to data
    923 h_line, h_patch = plot_xY(
    924     self.x_pred[self.running_variable_name],
    925     self.pred["posterior_predictive"].mu,
    926     ax=ax,
    927     plot_hdi_kwargs={"color": "C1"},
    928 )

File ~/anaconda3/lib/python3.9/site-packages/seaborn/_decorators.py:46, in _deprecate_positional_args.<locals>.inner_f(*args, **kwargs)
     36     warnings.warn(
     37         "Pass the following variable{} as {}keyword arg{}: {}. "
     38         "From version 0.12, the only valid positional argument "
   (...)
     43         FutureWarning
     44     )
     45 kwargs.update({k: arg for k, arg in zip(sig.parameters, args)})
---> 46 return f(**kwargs)

File ~/anaconda3/lib/python3.9/site-packages/seaborn/relational.py:808, in scatterplot(x, y, hue, style, size, data, palette, hue_order, hue_norm, sizes, size_order, size_norm, markers, style_order, x_bins, y_bins, units, estimator, ci, n_boot, alpha, x_jitter, y_jitter, legend, ax, **kwargs)
    793 @_deprecate_positional_args
    794 def scatterplot(
    795     *,
   (...)
    804     legend="auto", ax=None, **kwargs
    805 ):
    807     variables = _ScatterPlotter.get_semantics(locals())
--> 808     p = _ScatterPlotter(
    809         data=data, variables=variables,
    810         x_bins=x_bins, y_bins=y_bins,
    811         estimator=estimator, ci=ci, n_boot=n_boot,
    812         alpha=alpha, x_jitter=x_jitter, y_jitter=y_jitter, legend=legend,
    813     )
    815     p.map_hue(palette=palette, order=hue_order, norm=hue_norm)
    816     p.map_size(sizes=sizes, order=size_order, norm=size_norm)

File ~/anaconda3/lib/python3.9/site-packages/seaborn/relational.py:587, in _ScatterPlotter.__init__(self, data, variables, x_bins, y_bins, estimator, ci, n_boot, alpha, x_jitter, y_jitter, legend)
    571 def __init__(
    572     self, *,
    573     data=None, variables={},
   (...)
    581     # the kind of plot to draw, but for the time being we need to set
    582     # this information so the SizeMapping can use it
    583     self._default_size_range = (
    584         np.r_[.5, 2] * np.square(mpl.rcParams["lines.markersize"])
    585     )
--> 587     super().__init__(data=data, variables=variables)
    589     self.alpha = alpha
    590     self.legend = legend

File ~/anaconda3/lib/python3.9/site-packages/seaborn/_core.py:605, in VectorPlotter.__init__(self, data, variables)
    603 def __init__(self, data=None, variables={}):
--> 605     self.assign_variables(data, variables)
    607     for var, cls in self._semantic_mappings.items():
    608 
    609         # Create the mapping function
    610         map_func = partial(cls.map, plotter=self)

File ~/anaconda3/lib/python3.9/site-packages/seaborn/_core.py:668, in VectorPlotter.assign_variables(self, data, variables)
    666 else:
    667     self.input_format = "long"
--> 668     plot_data, variables = self._assign_variables_longform(
    669         data, **variables,
    670     )
    672 self.plot_data = plot_data
    673 self.variables = variables

File ~/anaconda3/lib/python3.9/site-packages/seaborn/_core.py:903, in VectorPlotter._assign_variables_longform(self, data, **kwargs)
    898 elif isinstance(val, (str, bytes)):
    899 
    900     # This looks like a column name but we don't know what it means!
    902     err = f"Could not interpret value `{val}` for parameter `{key}`"
--> 903     raise ValueError(err)
    905 else:
    906 
    907     # Otherwise, assume the value is itself data
    908 
    909     # Raise when data object is present and a vector can't matched
    910     if isinstance(data, pd.DataFrame) and not isinstance(val, pd.Series):

ValueError: Could not interpret value `all` for parameter `y`

**Comment by xinliy123** [comment] 2023-09-21 08:03
Any suggestions on this? Thanks in advance!

**Comment by jpreszler** [comment] 2023-09-21 23:28
@xinliy123 The code you're showing looks like it's from the regression discontinuity example (`rd_pymc_drinking.ipynb`) rather than the geolift example (`geolift1.ipynb`). Both notebooks run fine for me locally, but can you point to the specific example you're trying to reproduce?

Could you post the code that populates the dataframe `df` the entire call to the Regression Discontinuity experiment? My best guess given what I'm seeing is that the formula has a variable `all` but something is happening internally to make the 'output_variable_name' `y` which may be coming from the wrong data being loaded. Having the complete minimal code to reproduce the error would help diagnose further.

**Comment by drbenvincent** [comment] 2023-10-04 19:02
Closing due to lack of engagement. I can reopen if we get more info.

**Closed by drbenvincent** 2023-10-04 19:02 UTC
